# filename: nixpacks.toml
# Adiciona bibliotecas necessárias para rodar Chromium/Puppeteer em Linux/containers
[phases.setup]
aptPkgs = [
  "chromium-browser",
  "libglib2.0-0",
  "libnss3",
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxext6",
  "libxfixes3",
  "libxrandr2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libgbm1",
  "libpango-1.0-0",
  "libasound2",
  "libdrm2",
  "fonts-liberation",
  "libu2f-udev",
  "ca-certificates",
  "wget",
  "curl"
]
